config/routes.rb
Dursty::Application.routes.draw do

  get "sale_date/index"
  get "public/sale_dates"
  get "public/sale_dates_display"
  match "sale_date/:id/assign/:userid" => "sale_date#assign", :as => :sale_date_assign
  match "sale_date/:id/unassign/:userid" => "sale_date#unassign", :as => :sale_date_unassign

  devise_for :users

  resources :items
  resources :shop_bundles
  resources  :stock_changes
  get "stock/index"
  match "stock/showBundle/:id/:location" => "stock#showBundleAtLocation"
  match "items/:id/get-priceoptions" => "items#get_priceoptions", :as => :item_get_priceoptions
  match "stock/:id/sold-bundles/:from/:to" => "stock#sold_bundles", :as => :stock_get_sold_bundles

  scope "/admin" do
    resources :users
  end

  get "kasse/uebersicht"
  resources :konto_transactions
  resources :kontos

  get "shop/index"
  post "shop/buy"
  match "shop/add_bundle_to_card/:bundle/:amount" => 'shop#addBundleToCard', :as => :shop_add_bundle_to_card
  match "shop/remove_bundle_from_card/:bundle" => 'shop#removeBundleFromCard', :as => :shop_remove_bundle_from_card
  match "shop/order_part_item_amount/:order_part/:order_part_item_id/:amount" => 'shop#changeOrderPartItemAmount', :as => :shop_change_order_part_item
  resources :shop_bundle_categories

  match "userkonto/:id" => 'userkonto#show', :as => :userkonto_show

  resources :order
  match "order/:id/update/:bundle/:amount" => 'order#update_bundle_amount', :as => :order_update_bundle_amount
  match "order/:id/delete/:bundle" => 'order#delete_bundle', :as => :order_delete_bundle
  match "order/:id/part/:order_part/item/:order_part_item_id/:amount" => 'order#changePartItemAmount', :as => :order_change_part_item

  get "home/index"

  get "public/index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'public#index'

end

app/models/shop_bundle.rb
class ShopBundle < ActiveRecord::Base
  attr_accessible :id, :name, :positive, :shop_bundle_parts_attributes, :shop_bundle_category_ids, :image, :remove_image

  has_many :shop_bundle_parts
  accepts_nested_attributes_for :shop_bundle_parts, :allow_destroy => true, :reject_if => proc {|a| a['item_id'].blank? | a['amount'].blank? | a['item_price_id'].blank?}

  has_and_belongs_to_many :shop_bundle_categories
  has_many :items, :through => :shop_bundle_parts
  has_many :order_parts
  has_many :stock_changes

  # paperclip image
  has_attached_file :image,
    :removable => true,
    :styles => {:medium => "300x300>", :thumb => "100x100>", :xs => "50x50>"},
    :default_url => "/assets/missing.png"
  validates_attachment :image,
    :content_type => { :content_type => ["image/jpg","image/jpeg", "image/png"] },
    :size => { :in => 0..5.megabytes }

  def getTotalCost
    total = 0
    self.shop_bundle_parts.each do |p|
      return false unless p.item_price
      total += p.amount * p.item_price.price
    end

    total = total * (-1) unless self.positive

    return total
  end

  def inventory
    inv = {}
    self.shop_bundle_parts.each do |p|
      inv[p.item] = p.amount
    end
    return inv
  end
end

app/controllers/shop_bundles_controller.rb
# encoding: UTF-8

class ShopBundlesController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller|
    unless controller.check_role('admin','lagerwart')
      redirect_to root_path, :notice => 'Aktion nicht erlaubt'
    end
  end

  def index
    @bundles = ShopBundle.find(:all, :order => :name)
  end

  def new
    @bundle = ShopBundle.new
    @bundle.shop_bundle_parts.build
  end

  def edit
    @bundle = ShopBundle.find(params[:id])
  end

  def update
    #render :text => params.inspect and return
    @bundle = ShopBundle.find(params[:id])
    render :edit and return unless @bundle.update_attributes(params["shop_bundle"])
    redirect_to(shop_bundles_path, :notice => 'Shop bundle erfolgreich editiert.')
  end

  def create
    #render :text => params[:shop_bundle].inspect and return
    @bundle = ShopBundle.new params[:shop_bundle]
    render :new unless @bundle.save
    redirect_to(shop_bundles_path, :notice => 'Bundle erfolgreich angelegt.')
  end

  def destroy
    @bundle = ShopBundle.find params[:id]
    unless @bundle.shop_bundle_parts.destroy_all
      redirect_to(shop_bundles_path, :notice => 'Bundle-Parts nicht komplett gelöscht.')
    end
    unless @bundle.destroy
      redirect_to(shop_bundles_path, :notice => 'Bundle nicht gelöscht.')
    end
    redirect_to(shop_bundles_path, :notice => "Bundle erfolgreich gelöscht.")
  end

  def show
    render :text => "test" and return
  end

end

app/views/shop_bundles/_item.html.haml
%tr
  - if part.item_price
    %td= part.amount.to_s + "x " + part.item.name.to_s + " (" + number_to_currency(part.item_price.price, :unit => "€") + ")"
  - else
    %td="ERROR"

app/views/shop_bundles/_shop_bundle_part_fields.html.haml
%tr
  %td= f.input :item_id, :as => :select, :label => false, :collection => Item.all, :input_html => {:onchange => "item_get_prices(this);"}
  %td= f.input :amount, :label => false
  %td= f.input :item_price_id, :label => false, :as => :select, :collection => []
  %td= f.input "_destroy", :as => :boolean, :label => "Löschen?"
  %td= f.input :shop_bundle_id, :as => :hidden, :value => @bundle.id

app/views/shop_bundles/edit.html.haml
- content_for :pathway_sub do
  &raquo; Editiere "#{@bundle.name}"

= semantic_form_for @bundle, :url => shop_bundle_path, :method => :put, :html => { :multipart => true } do |f|
  = f.label :name, :required => true
  = f.text_field :name
  %br
  %br
  = f.label "Positiv"
  = f.radio_button :positive, 'true', :checked => @bundle.positive
  = f.label "Negativ"
  = f.radio_button :positive, 'false', :checked => !@bundle.positive

  %br
  %br
  %h2 Bild
  = image_tag(@bundle.image.url(:thumb))
  %br
  = f.file_field :image
  = f.input :remove_image, :as => :boolean, :label => "Löschen?" if f.object.image?
  %br
  %br

  %h2 Kategorien
  = f.input :shop_bundle_categories, :label => "", :as => :check_boxes, :collection => ShopBundleCategory.find(:all, :order => :name), :required => false

  %h2 Shop bundle Artikel
  %table
    %thead
      %td Artikel
      %td Anzahl
      %td Preisoption
    %tbody{:id => :shop_bundle_parts_tbody}
      = f.inputs :for => :shop_bundle_parts do |part, i|
        .nested-fields
          %tr
            %td= part.input :item_id, :as => :select, :label => false, :collection => Item.find(:all, :order => :name), :input_html => {:onchange => "item_get_prices(this);"}
            %td= part.input :amount, :label => false
            %td= part.input :item_price_id, :label => false, :as => :select, :collection => @bundle.shop_bundle_parts[i-1].item.item_prices.map{|price| ["#{price.name} (#{number_to_currency(price.price, :locale => :de)})",price.id]}
            %td= part.input "_destroy", :as => :boolean, :label => "Löschen?"
            %td= part.input :shop_bundle_id, :as => :hidden, :value => @bundle.id

  .links{:id => :shop_bundle_parts_links}
    = link_to_add_association 'weiteren Artikel', f, :shop_bundle_parts

  %br
  %br
  = f.actions do
    = f.action :cancel, :as => :link, :label => "abbrechen"
    = f.action :submit, :as => :button, :label => "speichern", :name => :update_bundle

:javascript
  $("#shop_bundle_parts_links a.add_fields").
    data("association-insertion-method", 'append').
    data("association-insertion-node", '#shop_bundle_parts_tbody')

app/views/shop_bundles/index.html.haml
%h1 Shop Bundles

%h2
  %a{:href => new_shop_bundle_path}
    Neues Bundle anlegen
    =image_tag "new.png", :width => "20px"
%br

%table{:class=> "table-index table-datatable"}
  %thead
    %tr
      %th Name
      %th Preis
      %th Artikel
      %th Kategorien
      %th
      %th
  %tbody
    - @bundles.each do |b|
      %tr{:class => "row_highlighted"}
        %td
          = b[:name]
          %br
          = image_tag(b.image.url(:thumb))
        - totalCost = b.getTotalCost
        - if totalCost
          - if b[:positive]
            %td{:class => "type_positive"}= number_to_currency(totalCost, :locale => :de)
          - else
            %td{:class => "type_negative"}= number_to_currency(totalCost, :locale => :de)
        - else
          %td ERROR
        %td
          %table
            = render :partial => "item", :collection => b.shop_bundle_parts, :as => "part"

        %td
          %ol
            - b.shop_bundle_categories.each do |c|
              %li=c.name
        %td= link_to(image_tag("edit.png", :width => "20px"), edit_shop_bundle_path(b["id"].to_i), :title => "Bundle editieren")
        %td= link_to(image_tag("delete.png", :width => "20px"),shop_bundle_path(b["id"].to_i), :title => "Bundle löschen", :method => :delete, :confirm => "Dieses Bundle wirklich löschen?")

app/views/shop_bundles/new.html.haml
- content_for :pathway_sub do
  &raquo; Neu

= semantic_form_for @bundle, :url => shop_bundles_path, :method => :post do |f|
  = f.label :name
  = f.text_field :name
  %br
  %br
  = f.label "Positiv"
  = f.radio_button :positive, 'true', :checked => true
  = f.label "Negativ"
  = f.radio_button :positive, 'false', :checked => false

  %br
  %br

  %h2 Kategorien
  = f.input :shop_bundle_categories, :label => "", :as => :check_boxes, :collection => ShopBundleCategory.find(:all, :order => :name), :required => false

  %h2 Neuen Artikel hinzufügen
  %table
    %thead
      %td Artikel
      %td Anzahl
      %td Preisoption
    %tbody{:id => :shop_bundle_parts_tbody}
      = f.inputs :for => :shop_bundle_parts do |part, i|
        .nested-fields
          %tr
            %td= part.input :item_id, :as => :select, :label => false, :collection => Item.find(:all, :order => :name), :input_html => {:onchange => "item_get_prices(this);"}
            %td= part.input :amount, :label => false
            - if @bundle.shop_bundle_parts[i-1].item
              %td= part.input :item_price_id, :label => false, :as => :select, :collection => @bundle.shop_bundle_parts[i-1].item.item_prices.map{|price| ["#{price.name} (#{number_to_currency(price.price, :locale => :de)})",price.id]}
            - else
              %td= part.input :item_price_id, :label => false, :as => :select, :collection => []
            %td= part.input "_destroy", :as => :boolean, :label => "Löschen?"
            %td= part.input :shop_bundle_id, :as => :hidden, :value => @bundle.id

  .links{:id => :shop_bundle_parts_links}
    = link_to_add_association 'weiteren Artikel', f, :shop_bundle_parts

  %br
  %br
  = f.actions do
    = f.action :cancel, :as => :link, :label => "abbrechen"
    = f.action :submit, :as => :button, :label => "speichern", :name => :update_bundle

:javascript
  $("#shop_bundle_parts_links a.add_fields").
    data("association-insertion-method", 'append').
    data("association-insertion-node", '#shop_bundle_parts_tbody')