config/routes.rb
Dursty::Application.routes.draw do

  get "sale_date/index"
  get "public/sale_dates"
  get "public/sale_dates_display"
  match "sale_date/:id/assign/:userid" => "sale_date#assign", :as => :sale_date_assign
  match "sale_date/:id/unassign/:userid" => "sale_date#unassign", :as => :sale_date_unassign

  devise_for :users

  resources :items
  resources :shop_bundles
  resources  :stock_changes
  get "stock/index"
  match "stock/showBundle/:id/:location" => "stock#showBundleAtLocation"
  match "items/:id/get-priceoptions" => "items#get_priceoptions", :as => :item_get_priceoptions
  match "stock/:id/sold-bundles/:from/:to" => "stock#sold_bundles", :as => :stock_get_sold_bundles

  scope "/admin" do
    resources :users
  end

  get "kasse/uebersicht"
  resources :konto_transactions
  resources :kontos

  get "shop/index"
  post "shop/buy"
  match "shop/add_bundle_to_card/:bundle/:amount" => 'shop#addBundleToCard', :as => :shop_add_bundle_to_card
  match "shop/remove_bundle_from_card/:bundle" => 'shop#removeBundleFromCard', :as => :shop_remove_bundle_from_card
  match "shop/order_part_item_amount/:order_part/:order_part_item_id/:amount" => 'shop#changeOrderPartItemAmount', :as => :shop_change_order_part_item
  resources :shop_bundle_categories

  match "userkonto/:id" => 'userkonto#show', :as => :userkonto_show

  resources :order
  match "order/:id/update/:bundle/:amount" => 'order#update_bundle_amount', :as => :order_update_bundle_amount
  match "order/:id/delete/:bundle" => 'order#delete_bundle', :as => :order_delete_bundle
  match "order/:id/part/:order_part/item/:order_part_item_id/:amount" => 'order#changePartItemAmount', :as => :order_change_part_item

  get "home/index"

  get "public/index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'public#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :closed, :id, :user_id, :stock_id

  validates_presence_of :user_id, :stock_id

  belongs_to :user
  has_many :order_parts
  has_many :order_part_items, :through => :order_parts
  has_many :items, :through => :order_part_items
  has_many :shop_bundles, :through => :order_parts
  has_many :user_account_bills, :through => :user
  belongs_to :stock

  scope :closed, where(:closed => true)

  @@expiration = 8

  def expired
    return self.created_at < @@expiration.days.ago.beginning_of_day
  end

  def updateParts shop_bundle_id, amount
    # check if bundle already in order
    part = OrderPart.where :order_id => self.id,
                           :shop_bundle_id => shop_bundle_id

    if part.size == 1
      # bundle exists in order, update amount
      part = part.first
      part.amount += amount.to_i
      # update amount of partItems
      return false unless part.updateBundleAmount shop_bundle_id, amount
      return part.save
    elsif part.size == 0
      # bundle not yet in order, create order_part and order_part_items
      bundle = ShopBundle.find shop_bundle_id
      part = OrderPart.new :order_id => self.id,
                           :shop_bundle_id => shop_bundle_id,
                           :amount => amount,
                           :positive => bundle.positive,
                           :name => bundle.name
      # save order part
      return false unless part.save

      # create order_part_items for order_part from shop_bundle_id
      #return part.createPartItems bundle
      return part.updateBundleAmount shop_bundle_id, amount
    else
      # error: more than one order_part for same shop_bundle
      return false
    end
  end

  def removePart shop_bundle_id
    # check if bundle in order
    part = OrderPart.where :order_id => self.id,
                           :shop_bundle_id => shop_bundle_id
    if part.size == 1
      # part exists in order, get first
      part = part.first

      # remove order_part_items
      return false unless part.removePartItems

      # remove order_part
      return part.destroy

    elsif part.size == 0
      # not existent in order, job done
      return true
    else
      # error: more than one order_part for same shop_bundle
      return false
    end

  end

  def gesamtpreis
    preis = 0
    self.order_parts.each do |p|
      preis += p.sumOfPartItems
    end

    return preis
  end

  def inventory
    inv = Hash.new(0)
    self.order_parts.each do |p|
      p.inventory.each do |item,amount|
        inv[item] += amount
      end
    end
    return inv
  end

  def soldBundles
    # build sold Bundles hash {bundle => {:bundleAmount => bAmount, :items => {item => iAmount}}
    res = {}
    self.order_parts.each do |p|
      res[p.shop_bundle] = {:bundleAmount => 0, :items => Hash.new(0)} unless res[p.shop_bundle]
      res[p.shop_bundle][:bundleAmount] += p.amount
      p.soldItems.each do |item, amount|
        res[p.shop_bundle][:items][item] += amount
      end
    end
    return res
  end
end

app/controllers/order_controller.rb
# encoding: UTF-8

class OrderController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller|
    # check if user owns order or user is admin/kassenwart
    unless controller.check_role('admin','kassenwart') || Order.find(params[:id]).user_id == current_user.id
      redirect_to(userkonto_show_path(current_user.id), :notice => 'Bestellung eines anderen Benutzers, Aktion nicht erlaubt.')
    end
  end

  before_filter do |controller|
    # unless user is admin/kassenwart, check if Order is not expired
    unless controller.check_role('admin','kassenwart')
      if Order.find(params[:id]).expired
        redirect_to(userkonto_show_path(current_user.id), :notice => 'Bestellung zu alt, nicht mehr editierbar.')
      end
    end
  end

  def edit
    @order = Order.find params[:id]
  end

  def update
    @order = Order.find params[:id]
    @order.stock = Stock.find(params[:order][:stock_id])
    if @order.save
      redirect_to(userkonto_show_path(@order.user_id), :notice => 'Bestellung erfolgreich editiert.')
    else
      render :edit and return
    end

  end

  def update_bundle_amount
    @order = Order.find params[:id]
    if @order.updateParts params[:bundle], params[:amount]
      @order.touch
      redirect_to(edit_order_path(@order.id), :notice => "Bestellung erfolgreich geändert.")
    else
      redirect_to(edit_order_path(@order.id), :notice => "Fehler aufgetreten, Bestellung nicht geändert.")
    end

  end

  def changePartItemAmount
    order = Order.find params[:id]
    part = order.order_parts.find params[:order_part]
    if part.updateItem(params[:order_part_item_id], params[:amount])
      part.touch
      redirect_to(edit_order_path(order.id), :notice => "Bestellung erfolgreich geändert.")
    else
      redirect_to(edit_order_path(order.id), :notice => "Fehler aufgetreten, Bestellung nicht geändert.")
    end
  end

  def delete_bundle
    @order = Order.find params[:id]
    if @order.removePart(params[:bundle])

      # check if order is empty now, then remove order
      unless @order.order_parts.size > 0
        @order.delete
        redirect_to(userkonto_show_path(@order.user_id), :notice => "Bestellung gelöscht.")
      else
        @order.touch
        redirect_to(edit_order_path(@order.id), :notice => "Erfolgreich aus der Bestellung entfernt.")
      end

    else
      redirect_to(edit_order_path(@order.id), :notice => "Fehler aufgetreten, nichts aus der Bestellung entfernt.")
    end

  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/_bundle.html.haml
%tr
  %td= item["amount"] + "x " + item["name"] + " (" + number_to_currency(item["price"], :unit => "€") + ")"

app/views/order/_item.html.haml
%tr
  - if positive
    %td{:class => "type_positive"}= part.amount.to_s + "x " + part.item.name.to_s + " (" + number_to_currency(part.item.preis, :locale => :de) + ")"
  - else
    %td{:class => "type_negative"}= part.amount.to_s + "x " + part.item.name.to_s + " (" + number_to_currency((-1)*part.item.preis, :locale => :de) + ")"

app/views/order/edit.html.haml
- content_for :pathway_sub do
  &raquo; Bestellung vom #{@order.created_at.strftime("%d.%m.%Y, %H:%M")}

- unless current_user.id == @order.user.id
  %h1=@order.user.name
  %h2 Bestellung vom #{@order.created_at.strftime("%d.%m.%Y, %H:%M")}
  %br

%table
  - @order.order_parts.each do |p|
    %tr
      %td
        %a{:href => order_update_bundle_amount_path(:id => @order.id, :bundle => p.shop_bundle_id, :amount => 1)}
          = image_tag "up.png", :class => "shop_more_bundle_part", :width => "15px"
        = p.amount.to_s + "x"
        - if p.amount > 1
          %a{:href => order_update_bundle_amount_path(:id => @order.id, :bundle => p.shop_bundle_id, :amount => -1)}
            = image_tag "down.png", :class => "shop_less_bundle_part", :width => "15px"

      %td=  p.name + " (" + number_to_currency(p.sumOfPartItems, :locale => :de) + ")"

      - if p.positive
        %td{:class => "type_positive cell_price"}=number_to_currency(p.sumOfPartItems, :locale => :de)
      - else
        %td{:class => "type_negative cell_price"}=number_to_currency(p.sumOfPartItems, :locale => :de)

      %td
        =link_to("",order_delete_bundle_path(:id => @order.id, :bundle => p.shop_bundle_id), :confirm => "Diesen Artikel wirklich löschen?", :class => "icon-trash", :title => "löschen")

    - p.order_part_items.each do |pi|
      %tr{:class => "bundle-item-list"}
        %td
        - if pi.order_part.positive; price = pi.price; else price = pi.price * (-1) end
        %td
          = link_to("", order_change_part_item_path(:order_part => p.id, :order_part_item_id => pi.id, :amount => 1), :class => "icon-chevron-up", :style => "color:grey", :title => "eröhen")
          - if pi.amount > 0
            = link_to("", order_change_part_item_path(:order_part => p.id, :order_part_item_id => pi.id, :amount => -1), :class => "icon-chevron-down", :style => "color:grey", :title => "verringern")
          = (pi.amount).to_s + "x " + pi.name + " (" + number_to_currency(price, :locale => :de) + ")"

  - unless @order.id.nil?
    %tr
      %td
      %td
      %td{:style => "text-align:center"} -------
    %tr
      %td
      %td{:style => "text-align:right"} Gesamtpreis:
      - gesamtpreis = @order.gesamtpreis
      - if gesamtpreis >= 0
        %td{:class => "type_positive cell_price"}=number_to_currency(gesamtpreis, :locale => :de)
      - else
        %td{:class => "type_negative cell_price"}=number_to_currency(gesamtpreis, :locale => :de)

= semantic_form_for @order do |f|
  = f.input :stock, :as => :select, :collection => @order.user.stocks, :label => "Verkaufsort", :include_blank => false
  = f.actions do
    = f.action :cancel, :as => :link, :label => "zurück zum Kassenstand", :url => userkonto_show_path(@order.user.id)
    = f.action :submit, :as => :button, :label => "Bestellung speichern"