config/routes.rb
Dursty::Application.routes.draw do

  get "sale_date/index"
  get "public/sale_dates"
  get "public/sale_dates_display"
  match "sale_date/:id/assign/:userid" => "sale_date#assign", :as => :sale_date_assign
  match "sale_date/:id/unassign/:userid" => "sale_date#unassign", :as => :sale_date_unassign

  devise_for :users

  resources :items
  resources :shop_bundles
  resources  :stock_changes
  get "stock/index"
  match "stock/showBundle/:id/:location" => "stock#showBundleAtLocation"
  match "items/:id/get-priceoptions" => "items#get_priceoptions", :as => :item_get_priceoptions
  match "stock/:id/sold-bundles/:from/:to" => "stock#sold_bundles", :as => :stock_get_sold_bundles

  scope "/admin" do
    resources :users
  end

  get "kasse/uebersicht"
  resources :konto_transactions
  resources :kontos

  get "shop/index"
  post "shop/buy"
  match "shop/add_bundle_to_card/:bundle/:amount" => 'shop#addBundleToCard', :as => :shop_add_bundle_to_card
  match "shop/remove_bundle_from_card/:bundle" => 'shop#removeBundleFromCard', :as => :shop_remove_bundle_from_card
  match "shop/order_part_item_amount/:order_part/:order_part_item_id/:amount" => 'shop#changeOrderPartItemAmount', :as => :shop_change_order_part_item
  resources :shop_bundle_categories

  match "userkonto/:id" => 'userkonto#show', :as => :userkonto_show

  resources :order
  match "order/:id/update/:bundle/:amount" => 'order#update_bundle_amount', :as => :order_update_bundle_amount
  match "order/:id/delete/:bundle" => 'order#delete_bundle', :as => :order_delete_bundle
  match "order/:id/part/:order_part/item/:order_part_item_id/:amount" => 'order#changePartItemAmount', :as => :order_change_part_item

  get "home/index"

  get "public/index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'public#index'

end

app/views/shared/_footer.html.haml
%p
  Getränke-AG OPH & TVK - Kontakt via
  %i{:class => "icon-envelope"}
  #{mail_to "getraenke@oph.rwth-aachen.de", "getraenke@oph.rwth-aachen.de"}

app/views/shared/_shoppingcard.html.haml
%div{:class => "shoppingcard"}
  %div{:class => "title"}
    %h2 Einkaufswagen
  - if @order.updated_at
    %p stand vom: #{@order.updated_at.strftime "%d.%m.%Y - %H:%M"}

  %table
    - @order.order_parts.sort{|a,b| b.created_at <=> a.created_at}.each do |p|
      %tr
        %td
          %a{:href => shop_add_bundle_to_card_path(:bundle => p.shop_bundle_id, :amount => 1, :category => params[:category])}
            = image_tag "up.png", :class => "shop_more_bundle_part", :width => "15px"
          = p.amount.to_s + "x"
          - if p.amount > 1
            %a{:href => shop_add_bundle_to_card_path(:bundle => p.shop_bundle_id, :amount => -1, :category => params[:category])}
              = image_tag "down.png", :class => "shop_less_bundle_part", :width => "15px"
        %td=  p.name
        - if p.positive
          %td{:class => "type_positive cell_price"}=number_to_currency(p.sumOfPartItems, :locale => :de)
        - else
          %td{:class => "type_negative cell_price"}=number_to_currency(p.sumOfPartItems, :locale => :de)
        %td
          =link_to("", shop_remove_bundle_from_card_path(:bundle => p.shop_bundle_id, :category => params[:category]), :title => "Artikel löschen", :class => "icon-trash", :confirm => "Diesen Artikel wirklich löschen?")

      - p.order_part_items.each do |pi|
        %tr{:class => "bundle-item-list"}
          %td
          - if pi.order_part.positive; price = pi.price; else price = pi.price * (-1) end
          %td
            = link_to("", shop_change_order_part_item_path(:order_part => p.id, :order_part_item_id => pi.id, :amount => 1), :class => "icon-chevron-up", :style => "color:grey", :title => "eröhen")
            - if pi.amount > 0
              = link_to("", shop_change_order_part_item_path(:order_part => p.id, :order_part_item_id => pi.id, :amount => -1), :class => "icon-chevron-down", :style => "color:grey", :title => "verringern")
            = pi.amount.to_s + "x " + pi.name + " (" + number_to_currency(price, :locale => :de) + ")"

    - unless @order.id.nil?
      %tr
        %td
        %td
        %td{:style => "text-align:center"} -------
      %tr
        %td
        %td{:style => "text-align:right"} Gesamtpreis:
        - gesamtpreis = @order.gesamtpreis
        - if gesamtpreis >= 0
          %td{:class => "type_positive cell_price"}=number_to_currency(gesamtpreis, :locale => :de)
        - else
          %td{:class => "type_negative cell_price"}=number_to_currency(gesamtpreis, :locale => :de)


  %br
  = semantic_form_for @order, :url => shop_buy_path, :method => :post do |f|
    = f.input :stock, :as => :select, :collection => @user.stocks, :label => "Verkaufsort", :include_blank => false
    = f.actions do
      = f.action :submit, :as => :button, :label => "Kauf abschliessen"