config/routes.rb
Dursty::Application.routes.draw do

  get "sale_date/index"
  get "public/sale_dates"
  get "public/sale_dates_display"
  match "sale_date/:id/assign/:userid" => "sale_date#assign", :as => :sale_date_assign
  match "sale_date/:id/unassign/:userid" => "sale_date#unassign", :as => :sale_date_unassign

  devise_for :users

  resources :items
  resources :shop_bundles
  resources  :stock_changes
  get "stock/index"
  match "stock/showBundle/:id/:location" => "stock#showBundleAtLocation"
  match "items/:id/get-priceoptions" => "items#get_priceoptions", :as => :item_get_priceoptions
  match "stock/:id/sold-bundles/:from/:to" => "stock#sold_bundles", :as => :stock_get_sold_bundles

  scope "/admin" do
    resources :users
  end

  get "kasse/uebersicht"
  resources :konto_transactions
  resources :kontos

  get "shop/index"
  post "shop/buy"
  match "shop/add_bundle_to_card/:bundle/:amount" => 'shop#addBundleToCard', :as => :shop_add_bundle_to_card
  match "shop/remove_bundle_from_card/:bundle" => 'shop#removeBundleFromCard', :as => :shop_remove_bundle_from_card
  match "shop/order_part_item_amount/:order_part/:order_part_item_id/:amount" => 'shop#changeOrderPartItemAmount', :as => :shop_change_order_part_item
  resources :shop_bundle_categories

  match "userkonto/:id" => 'userkonto#show', :as => :userkonto_show

  resources :order
  match "order/:id/update/:bundle/:amount" => 'order#update_bundle_amount', :as => :order_update_bundle_amount
  match "order/:id/delete/:bundle" => 'order#delete_bundle', :as => :order_delete_bundle
  match "order/:id/part/:order_part/item/:order_part_item_id/:amount" => 'order#changePartItemAmount', :as => :order_change_part_item

  get "home/index"

  get "public/index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'public#index'

end

app/models/stock_change.rb
class StockChange < ActiveRecord::Base
  attr_accessible :shop_bundle_id, :stock_id, :amount, :name

  belongs_to :shop_bundle
  belongs_to :stock

  def inventory
    inv = self.shop_bundle.inventory
    inv.each do |item, amount|
      inv[item] = amount * self.amount
    end
    return inv
  end
end

app/controllers/stock_changes_controller.rb
# encoding: UTF-8
class StockChangesController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller|
    unless controller.check_role('admin','lagerwart') || User.find(params[:id]).id == current_user.id
      redirect_to root_path, :notice => 'Aktion nicht erlaubt'
    end
  end

  def index
    @stock = Stock.find params[:stock]
    @stock_changes = StockChange.where(:stock_id => @stock.id).order("created_at DESC")
  end

  def new
    @stock_change = StockChange.new
    if params[:stock]
      @stock_change[:stock_id] = params[:stock]
    end
    @bundles = ShopBundle.all.map{|b| [b.name+" ("+b.getTotalCost.to_s+")", b.id]}
    @stocks = Stock.all
  end

  def create
    stock_change = StockChange.new params[:stock_change]
    if stock_change.save
      redirect_to stock_changes_path(:stock => stock_change.stock.id), :notice => 'Lageränderung gespeichert.'
    else
      render :new
    end
  end

  def edit
    @stock_change = StockChange.find params[:id]
    @bundles = ShopBundle.all.map{|b| [b.name+" ("+b.getTotalCost.to_s+")", b.id]}
    @stocks = Stock.all
  end

  def update
    stock_change = StockChange.find params[:id]
    if stock_change.update_attributes params[:stock_change]
      redirect_to stock_changes_path(:stock => stock_change.stock.id), :notice => 'Lageränderung gespeichert.'
    else
      render :edit
    end
  end

  def destroy
    stock_change = StockChange.find params[:id]
    if stock_change.destroy
      redirect_to(stock_changes_path(:stock => stock_change.stock.id), :notice => 'Lageränderung erfolgreich gelöscht.')
    else
      redirect_to(stock_changes_path(:stock => stock_change.stock.id), :notice => 'Lageränderung nicht gelöscht.')
    end
  end
end

app/helpers/stock_change_helper.rb
module StockChangeHelper
end

app/views/stock_changes/edit.html.haml
- content_for :pathway_sub do
  &raquo; Bearbeiten

= semantic_form_for @stock_change do |f|
  = f.input :stock_id, :as => :select, :collection => @stocks, :include_blank => false, :label => "Lager"
  = f.input :shop_bundle_id, :as => :select, :collection => @bundles
  = f.input :amount, :label => "Anzahl"
  = f.input :name, :label => "Grund"
  = f.actions

app/views/stock_changes/index.html.haml
- content_for :pathway_sub do
  &raquo; Änderungen im Lager #{@stock.name.upcase}

%div{:class => "konto-detail"}
  %h1 Lager #{@stock.name.upcase}

%h2
  %a{:href => new_stock_change_path(:stock => @stock.id)}
    Neue Lageränderung
    =image_tag "new.png", :width => "20px"
%br

  %table{:class=> "table-index table_bills"}
    %thead
      %tr
        %th Datum
        %th Shop Bundle
        %th Menge
        %th Grund
        %th
        %th
    %tbody
      -@stock_changes.each do |sc|
        %tr{:class => "toggle_background"}
          %td=sc.created_at.strftime("%d.%m.%Y")
          %td=sc.shop_bundle.name
          %td=sc.amount
          %td=sc.name
          %td
            =link_to(image_tag("edit.png", :width => "20px", :title => "Lageränderung editieren"), edit_stock_change_path(sc.id))
          %td
            =link_to(image_tag("delete.png", :width => "20px", :title => "Lageränderung löschen"), stock_change_path(sc.id), :method => :delete, :confirm => "Wirklich löschen?")

app/views/stock_changes/new.html.haml
- content_for :pathway_sub do
  &raquo; Neue Lageränderung

= semantic_form_for @stock_change do |f|
  = f.input :stock_id, :as => :select, :collection => @stocks, :include_blank => false, :label => "Lager"
  = f.input :shop_bundle_id, :as => :select, :collection => @bundles
  = f.input :amount, :label => "Anzahl"
  = f.input :name, :label => "Grund"
  = f.actions